### ISSUE TITLE
DocToText, data extraction, XLSX - Blank cells are not reported

### ISSUE THREAD

**Issue by Ferid456** [docwire/doctotext#21]
When extracting data through DocToText from Microsoft Excel, I noticed that blank cells are not reported. Is there any way to recognize blank cells? 
![Xlsx 1](https://github.com/docwire/doctotext/assets/118486294/8615e911-5f30-4659-a5a2-3ee778495bfb)
![Xlsx2](https://github.com/docwire/doctotext/assets/118486294/4ab20382-349c-42c9-b59f-af6712f95f87)

**Comment by as-ascii** [comment]
The problem is very interesting. According to the official documentation of Office Open XML format blank spreadsheet cells or even whole rows can be just skipped when saving. There are simply no tags for that in the original file so DocWire DocToText SDK is not generating row and cell signals then. Not an easy situation for a programmer/user if proper layout information is required.

We discussed what should be the correct behavior in this situation. Since every row tag in XLSX file has the row number attribute and every cell tag in XLSX file has cell address attribute (like "B4") we decided to implement a special algorithm to reconstruct missing rows and cells in the layout just like the real spreadsheet application does.

When SDK is extracting data from XLSX file it is is tracking next expected row number and next expected column number. If the row number or cell address parsed from the tag attribute in original file is larger than the expected one, SDK generates signals for missing empty spreadsheet rows and cells. This way the problem does not exist for user application no matter what the spreadsheet format is: XLSX, XLS, ODS or even more exotic ones like FODS.

You can find the new version in the pull request currently and it will soon (after some testing procedures) be available in the master branch and then in 6.0 release. Please take a look how it is working now on the screenshots below:
![obraz](https://github.com/docwire/doctotext/assets/62467072/141b7cf8-277a-49a8-9330-cd5b5774677b)
![obraz](https://github.com/docwire/doctotext/assets/62467072/95ef5f97-f353-477b-bd2e-a331d197defe)
![obraz](https://github.com/docwire/doctotext/assets/62467072/1003867c-46de-4eda-ba1d-468eb8b26bd4)

**Comment by tomaszpalasz** [comment]
I've tested new build that supports sending additional signals for cells but I got following error if we have any data in columns J to Z. It is working fine for data A-I and past AA.
Error processing file ../1.xlsx. Unknown error.
I used both Google Docs and Libre Office to create xlsx file and I got this error for Linux build (OpenSuse Tumbleweed) and Windows (mingw and msvc builds)>

![image](https://github.com/docwire/doctotext/assets/87810713/e4cb45d4-a74a-4e7a-8e07-c6fe90bfd3ad)
