### ISSUE TITLE
text_extractor.sh stuck on this PDF file while extracting text

### ISSUE THREAD

**Issue by tomaszpalasz** [docwire/doctotext#23]
I was trying to extract text from the file attached but the process does not finish. It's stuck for longer period of time.
[deuar-phd2.pdf](https://github.com/docwire/doctotext/files/11903337/deuar-phd2.pdf)

**Comment by tomaszpalasz** [comment]
[geo_20_07.pdf](https://github.com/docwire/doctotext/files/11914228/geo_20_07.pdf)

This file also causes the problem.

**Comment by as-ascii** [comment]
The problem was analyzed, an error was detected and the fix is applied in pull request connected to this issue. Please retest. The bug was caused by incorrect code when parsing PDF files with font that is unknown for the SDK. It should not be a common issue because PDF parser supports all basic fonts, containing Adobe CMaps but these documents are specific. DocToText SDK uses font data to calculate positions and sizes of characters, paragraphs etc to recreate PDF layout when converting to other document formats so the output will not be perfect unfortunately. If an improvement is required for this please open a new issue.

**Comment by tomaszpalasz** [comment]
Thank you. I've tried to extract text from those two documents using new version of DocToText SDK (text_extractor application) and both documents were processed.
