### ISSUE TITLE
EML File - segmentation fault while processing e-mail with unsupported attachment

### ISSUE THREAD

**Issue by tomaszpalasz** [docwire/doctotext#26]
![image](https://github.com/docwire/doctotext/assets/87810713/015aaca1-7b10-4aed-87cf-16af836c4300)
I was working with Doctotext to process various e-mail data (PST, OST, EML files). Doctotext was able to extract text both from the message and the attachments.
I faced the problem when I tried to extract text from EML file with AVI attachment. Suspicion fell on the format of the attachment so I created an EML file with attachment in xyz extension. I attach the error message

**Comment by as-ascii** [comment]
EML parser in C++ library as well as in CLI utility parses all embedded attachments indeed, even EML inside EML (that sometimes happens when emails are forwarded).
EML is a very popular format (Microsoft Outlook, Lotus Notes, Windows Mail, Mozilla Thunderbird and other email clients) so the bug needs quick reaction and... It's already fixed in attached pull request ;-)
If everything is fine it will be merged to 5.0.x branch and master branch.

**Comment by as-ascii** [comment]
Merged into 5.0.x branch.
