### ISSUE TITLE
Fixed VCPKG repository revision, removing docker layer

### ISSUE THREAD

**Issue by tomaszpalasz** [docwire/doctotext#33]
MSVC build scripts (release and debug versions) use fixed VCPKG repository revision only for part of dependencies, then it is switched to “latest”. There are a lot of copy commands for libraries and headers to duplicate them from the vcpkg directory to other directories that will be not compatible in case of creating doctotext own vcpkg package.

**Comment by as-ascii** [comment]
Build script for MSVC binaries were refactored. VCPKG is used with tag 2023.01.09 on all platforms to guarantee stable and predictable build process (upgrade to newer requires more work).
Some tricks were required to use this older tag because required MSYS packages are not available on mirrors any more so be patched vcpkg script to use newer ones.
Changes are currently available in master branch.
